import {AttackSpeedModifier} from "./AttackSpeedModifier.tsx";

export const AttackSpeedModifiers = [
    new AttackSpeedModifier("プラスパワー(+25)", () => 25),
    new AttackSpeedModifier("手助け(+35)", () => 35),
    new AttackSpeedModifier("コーチング(+40)", () => 40),
    new AttackSpeedModifier("フェイント、つじぎり(+60,アブソル)", () => 60, "Absol"),
    new AttackSpeedModifier("ブレードフォルム(+15,ギルガルド)", () => 15, "Aegislash"),
    new AttackSpeedModifier("アクアテール(+20,マリルリ)", () => 20, "Azumarill"),
    new AttackSpeedModifier("パンチスタイル(+40,バシャーモ)", () => 40, "Blaziken"),
    new AttackSpeedModifier("ビーストブースト(+25,マッシブーン)", () => 25, "Buzzwole"),
    new AttackSpeedModifier("とびかかる(+30,マッシブーン)", () => 30, "Buzzwole"),
    new AttackSpeedModifier("ニトロチャージ(+20,ソウブレイズ)", () => 20, "Ceruledge"),
    new AttackSpeedModifier("もうか(+20,エースバーン)", () => 20, "Cinderace"),
    new AttackSpeedModifier("ブレイズキック+(+65,エースバーン)", () => 65, "Cinderace"),
    new AttackSpeedModifier("ブレイズストライク(+35,エースバーン)", () => 35, "Cinderace"),
    new AttackSpeedModifier("通常攻撃最大スタック(+12,ジュナイパー)", () => 12, "Decidueye"),
    new AttackSpeedModifier("このは(+25,ジュナイパー)", () => 25, "Decidueye"),
    new AttackSpeedModifier("はっぱカッター(+40~52[レベルで変動],ジュナイパー)", (level: number) => (level - 1) + 40, "Decidueye"),
    new AttackSpeedModifier("でんこうせっか(+40,ドラパルト)", () => 40, "Dragapult"),
    new AttackSpeedModifier("ゴーストダイブ(+85,ドラパルト)", () => 85, "Dragapult"),
    new AttackSpeedModifier("りゅうのまい(+80,カイリュー)", () => 80, "Dragonite"),
    new AttackSpeedModifier("げきりん(+30,カイリュー)", () => 30, "Dragonite"),
    new AttackSpeedModifier("りゅうせいラッシュ(+35,カイリュー)", () => 30, "Dragonite"),
    new AttackSpeedModifier("ラスターカノン(+100[5秒に渡って減衰する],ジュラルドン)", () => 100, "Duraludon"),
    new AttackSpeedModifier("ラスターカノン(+80[5秒に渡って減衰する],ジュラルドン)", () => 80, "Duraludon"),
    new AttackSpeedModifier("ラスターカノン(+60[5秒に渡って減衰する],ジュラルドン)", () => 60, "Duraludon"),
    new AttackSpeedModifier("ラスターカノン(+40[5秒に渡って減衰する],ジュラルドン)", () => 40, "Duraludon"),
    new AttackSpeedModifier("ラスターカノン(+20[5秒に渡って減衰する],ジュラルドン)", () => 20, "Duraludon"),
    new AttackSpeedModifier("ビルドアップ(+25,タイレーツ)", () => 25, "Falinks"),
    new AttackSpeedModifier("通常攻撃最大スタック(+28~70[レベルで変動],ガブリアス)", (level: number) => 3 * (level - 1) + 28, "Garchomp"),
    new AttackSpeedModifier("すなかけ(+30,ガブリアス)", () => 30, "Garchomp"),
    new AttackSpeedModifier("こおりのつぶて(+60,グレイシア)", () => 60, "Glaceon"),
    new AttackSpeedModifier("こおりのつぶて+(+100,グレイシア)", () => 100, "Glaceon"),
    new AttackSpeedModifier("ダイヤモンドステージ(+35,グレイシア)", () => 35, "Glaceon"),
    
]
